import { Inter } from "next/font/google";
import "./globals.scss";
import Footer from "@/components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "infinitychassis | Ambulance Configuration ToolCreate Next App",
  description: "Generated by inovaForce",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'inter.className d-flex flex-column  h-screen'}>
        {children}
        <Footer />        
        </body>
    </html>
  );
}
